// ? Defining different types of actions that impact state.
// ? Using data- and error-handling to ensure data is only
// ? loaded when needed.

// ! WAIT FOR USERS

// TODO: TICKER
export const REQ_TICKER_PENDING = 'REQ_TICKER_PENDING';
export const REQ_TICKER_SUCCESS = 'REQ_TICKER_SUCCESS';
export const REQ_TICKER_ERROR = 'REQ_TICKER_ERROR';

export const ADD_TICKER_PENDING = 'ADD_TICKER_PENDING';
export const ADD_TICKER_SUCCESS = 'ADD_TICKER_SUCCESS';
export const ADD_TICKER_ERROR = 'ADD_TICKER_ERROR';

export const UPDATE_TICKER_PENDING = 'UPDATE_TICKER_PENDING';
export const UPDATE_TICKER_SUCCESS = 'UPDATE_TICKER_SUCCESS';
export const UPDATE_TICKER_ERROR = 'UPDATE_TICKER_ERROR';

export const DELETE_TICKER_PENDING = 'DELETE_TICKER_PENDING';
export const DELETE_TICKER_SUCCESS = 'DELETE_TICKER_SUCCESS';
export const DELETE_TICKER_ERROR = 'DELETE_TICKER_ERROR';

// TODO: NOTE

export const REQ_NOTE_PENDING = 'REQ_NOTE_PENDING';
export const REQ_NOTE_SUCCESS = 'REQ_NOTE_SUCCESS';
export const REQ_NOTE_ERROR = 'REQ_NOTE_ERROR';

export const ADD_NOTE_PENDING = 'ADD_NOTE_PENDING';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_ERROR = 'ADD_NOTE_ERROR';

export const UPDATE_NOTE_PENDING = 'UPDATE_NOTE_PENDING';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_ERROR = 'UPDATE_NOTE_ERROR';

export const DELETE_NOTE_PENDING = 'DELETE_NOTE_PENDING';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR';

// TODO: JOURNAL

export const REQ_JOURNAL_PENDING = 'REQ_JOURNAL_PENDING';
export const REQ_JOURNAL_SUCCESS = 'REQ_JOURNAL_SUCCESS';
export const REQ_JOURNAL_ERROR = 'REQ_JOURNAL_ERROR';

export const ADD_JOURNAL_PENDING = 'ADD_JOURNAL_PENDING';
export const ADD_JOURNAL_SUCCESS = 'ADD_JOURNAL_SUCCESS';
export const ADD_JOURNAL_ERROR = 'ADD_JOURNAL_ERROR';

export const UPDATE_JOURNAL_PENDING = 'UPDATE_JOURNAL_PENDING';
export const UPDATE_JOURNAL_SUCCESS = 'UPDATE_JOURNAL_SUCCESS';
export const UPDATE_JOURNAL_ERROR = 'UPDATE_JOURNAL_ERROR';

export const DELETE_JOURNAL_PENDING = 'DELETE_JOURNAL_PENDING';
export const DELETE_JOURNAL_SUCCESS = 'DELETE_JOURNAL_SUCCESS';
export const DELETE_JOURNAL_ERROR = 'DELETE_JOURNAL_ERROR';

// TODO: BOOKMARKS

export const REQ_BOOKMARK_PENDING = 'REQ_BOOKMARK_PENDING';
export const REQ_BOOKMARK_SUCCESS = 'REQ_BOOKMARK_SUCCESS';
export const REQ_BOOKMARK_ERROR = 'REQ_BOOKMARK_ERROR';

export const ADD_BOOKMARK_PENDING = 'ADD_BOOKMARK_PENDING';
export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const ADD_BOOKMARK_ERROR = 'ADD_BOOKMARK_ERROR';

export const UPDATE_BOOKMARK_PENDING = 'UPDATE_BOOKMARK_PENDING';
export const UPDATE_BOOKMARK_SUCCESS = 'UPDATE_BOOKMARK_SUCCESS';
export const UPDATE_BOOKMARK_ERROR = 'UPDATE_BOOKMARK_ERROR';

export const DELETE_BOOKMARK_PENDING = 'DELETE_BOOKMARK_PENDING';
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
export const DELETE_BOOKMARK_ERROR = 'DELETE_BOOKMARK_ERROR';

// TODO: BLOCK

export const REQ_BLOCK_PENDING = 'REQ_BLOCK_PENDING';
export const REQ_BLOCK_SUCCESS = 'REQ_BLOCK_SUCCESS';
export const REQ_BLOCK_ERROR = 'REQ_BLOCK_ERROR';

export const ADD_BLOCK_PENDING = 'ADD_BLOCK_PENDING';
export const ADD_BLOCK_SUCCESS = 'ADD_BLOCK_SUCCESS';
export const ADD_BLOCK_ERROR = 'ADD_BLOCK_ERROR';

export const UPDATE_BLOCK_PENDING = 'UPDATE_BLOCK_PENDING';
export const UPDATE_BLOCK_SUCCESS = 'UPDATE_BLOCK_SUCCESS';
export const UPDATE_BLOCK_ERROR = 'UPDATE_BLOCK_ERROR';

export const DELETE_BLOCK_PENDING = 'DELETE_BLOCK_PENDING';
export const DELETE_BLOCK_SUCCESS = 'DELETE_BLOCK_SUCCESS';
export const DELETE_BLOCK_ERROR = 'DELETE_BLOCK_ERROR';
