// ? Defining different types of actions that impact state.
// ? Using data- and error-handling to ensure data is only
// ? loaded when needed.

// ! WAIT FOR USERS

// ? TICKER
export const REQ_TICKER_PENDING = 'REQ_TICKER_PENDING';
export const REQ_TICKER_SUCCESS = 'REQ_TICKER_SUCCESS';
export const REQ_TICKER_ERROR = 'REQ_TICKER_ERROR';

export const ADD_TICKER_PENDING = 'ADD_TICKER_PENDING';
export const ADD_TICKER_SUCCESS = 'ADD_TICKER_SUCCESS';
export const ADD_TICKER_ERROR = 'ADD_TICKER_ERROR';

export const UPDATE_TICKER_PENDING = 'UPDATE_TICKER_PENDING';
export const UPDATE_TICKER_SUCCESS = 'UPDATE_TICKER_SUCCESS';
export const UPDATE_TICKER_ERROR = 'UPDATE_TICKER_ERROR';

export const DELETE_TICKER_PENDING = 'DELETE_TICKER_PENDING';
export const DELETE_TICKER_SUCCESS = 'DELETE_TICKER_SUCCESS';
export const DELETE_TICKER_ERROR = 'DELETE_TICKER_ERROR';

// ? TICKERS
export const REQ_TICKERS_PENDING = 'REQ_TICKERS_PENDING';
export const REQ_TICKERS_SUCCESS = 'REQ_TICKERS_SUCCESS';
export const REQ_TICKERS_ERROR = 'REQ_TICKERS_ERROR';

export const ADD_TICKERS_PENDING = 'ADD_TICKERS_PENDING';
export const ADD_TICKERS_SUCCESS = 'ADD_TICKERS_SUCCESS';
export const ADD_TICKERS_ERROR = 'ADD_TICKERS_ERROR';

export const UPDATE_TICKERS_PENDING = 'UPDATE_TICKERS_PENDING';
export const UPDATE_TICKERS_SUCCESS = 'UPDATE_TICKERS_SUCCESS';
export const UPDATE_TICKERS_ERROR = 'UPDATE_TICKERS_ERROR';

export const DELETE_TICKERS_PENDING = 'DELETE_TICKERS_PENDING';
export const DELETE_TICKERS_SUCCESS = 'DELETE_TICKERS_SUCCESS';
export const DELETE_TICKERS_ERROR = 'DELETE_TICKERS_ERROR';

// ? NOTE
export const REQ_NOTE_PENDING = 'REQ_NOTE_PENDING';
export const REQ_NOTE_SUCCESS = 'REQ_NOTE_SUCCESS';
export const REQ_NOTE_ERROR = 'REQ_NOTE_ERROR';

export const ADD_NOTE_PENDING = 'ADD_NOTE_PENDING';
export const ADD_NOTE_SUCCESS = 'ADD_NOTE_SUCCESS';
export const ADD_NOTE_ERROR = 'ADD_NOTE_ERROR';

export const UPDATE_NOTE_PENDING = 'UPDATE_NOTE_PENDING';
export const UPDATE_NOTE_SUCCESS = 'UPDATE_NOTE_SUCCESS';
export const UPDATE_NOTE_ERROR = 'UPDATE_NOTE_ERROR';

export const DELETE_NOTE_PENDING = 'DELETE_NOTE_PENDING';
export const DELETE_NOTE_SUCCESS = 'DELETE_NOTE_SUCCESS';
export const DELETE_NOTE_ERROR = 'DELETE_NOTE_ERROR';

// ? NOTES
export const REQ_NOTES_PENDING = 'REQ_NOTES_PENDING';
export const REQ_NOTES_SUCCESS = 'REQ_NOTES_SUCCESS';
export const REQ_NOTES_ERROR = 'REQ_NOTES_ERROR';

export const ADD_NOTES_PENDING = 'ADD_NOTES_PENDING';
export const ADD_NOTES_SUCCESS = 'ADD_NOTES_SUCCESS';
export const ADD_NOTES_ERROR = 'ADD_NOTES_ERROR';

export const UPDATE_NOTES_PENDING = 'UPDATE_NOTES_PENDING';
export const UPDATE_NOTES_SUCCESS = 'UPDATE_NOTES_SUCCESS';
export const UPDATE_NOTES_ERROR = 'UPDATE_NOTES_ERROR';

export const DELETE_NOTES_PENDING = 'DELETE_NOTES_PENDING';
export const DELETE_NOTES_SUCCESS = 'DELETE_NOTES_SUCCESS';
export const DELETE_NOTES_ERROR = 'DELETE_NOTES_ERROR';

// ? JOURNAL
export const REQ_JOURNAL_PENDING = 'REQ_JOURNAL_PENDING';
export const REQ_JOURNAL_SUCCESS = 'REQ_JOURNAL_SUCCESS';
export const REQ_JOURNAL_ERROR = 'REQ_JOURNAL_ERROR';

export const ADD_JOURNAL_PENDING = 'ADD_JOURNAL_PENDING';
export const ADD_JOURNAL_SUCCESS = 'ADD_JOURNAL_SUCCESS';
export const ADD_JOURNAL_ERROR = 'ADD_JOURNAL_ERROR';

export const UPDATE_JOURNAL_PENDING = 'UPDATE_JOURNAL_PENDING';
export const UPDATE_JOURNAL_SUCCESS = 'UPDATE_JOURNAL_SUCCESS';
export const UPDATE_JOURNAL_ERROR = 'UPDATE_JOURNAL_ERROR';

export const DELETE_JOURNAL_PENDING = 'DELETE_JOURNAL_PENDING';
export const DELETE_JOURNAL_SUCCESS = 'DELETE_JOURNAL_SUCCESS';
export const DELETE_JOURNAL_ERROR = 'DELETE_JOURNAL_ERROR';

// ? JOURNALS
export const REQ_JOURNALS_PENDING = 'REQ_JOURNALS_PENDING';
export const REQ_JOURNALS_SUCCESS = 'REQ_JOURNALS_SUCCESS';
export const REQ_JOURNALS_ERROR = 'REQ_JOURNALS_ERROR';

export const ADD_JOURNALS_PENDING = 'ADD_JOURNALS_PENDING';
export const ADD_JOURNALS_SUCCESS = 'ADD_JOURNALS_SUCCESS';
export const ADD_JOURNALS_ERROR = 'ADD_JOURNALS_ERROR';

export const UPDATE_JOURNALS_PENDING = 'UPDATE_JOURNALS_PENDING';
export const UPDATE_JOURNALS_SUCCESS = 'UPDATE_JOURNALS_SUCCESS';
export const UPDATE_JOURNALS_ERROR = 'UPDATE_JOURNALS_ERROR';

export const DELETE_JOURNALS_PENDING = 'DELETE_JOURNALS_PENDING';
export const DELETE_JOURNALS_SUCCESS = 'DELETE_JOURNALS_SUCCESS';
export const DELETE_JOURNALS_ERROR = 'DELETE_JOURNALS_ERROR';

// ? BOOKMARK
export const REQ_BOOKMARK_PENDING = 'REQ_BOOKMARK_PENDING';
export const REQ_BOOKMARK_SUCCESS = 'REQ_BOOKMARK_SUCCESS';
export const REQ_BOOKMARK_ERROR = 'REQ_BOOKMARK_ERROR';

export const ADD_BOOKMARK_PENDING = 'ADD_BOOKMARK_PENDING';
export const ADD_BOOKMARK_SUCCESS = 'ADD_BOOKMARK_SUCCESS';
export const ADD_BOOKMARK_ERROR = 'ADD_BOOKMARK_ERROR';

export const UPDATE_BOOKMARK_PENDING = 'UPDATE_BOOKMARK_PENDING';
export const UPDATE_BOOKMARK_SUCCESS = 'UPDATE_BOOKMARK_SUCCESS';
export const UPDATE_BOOKMARK_ERROR = 'UPDATE_BOOKMARK_ERROR';

export const DELETE_BOOKMARK_PENDING = 'DELETE_BOOKMARK_PENDING';
export const DELETE_BOOKMARK_SUCCESS = 'DELETE_BOOKMARK_SUCCESS';
export const DELETE_BOOKMARK_ERROR = 'DELETE_BOOKMARK_ERROR';

// ? BOOKMARKS
export const REQ_BOOKMARKS_PENDING = 'REQ_BOOKMARKS_PENDING';
export const REQ_BOOKMARKS_SUCCESS = 'REQ_BOOKMARKS_SUCCESS';
export const REQ_BOOKMARKS_ERROR = 'REQ_BOOKMARKS_ERROR';

export const ADD_BOOKMARKS_PENDING = 'ADD_BOOKMARKS_PENDING';
export const ADD_BOOKMARKS_SUCCESS = 'ADD_BOOKMARKS_SUCCESS';
export const ADD_BOOKMARKS_ERROR = 'ADD_BOOKMARKS_ERROR';

export const UPDATE_BOOKMARKS_PENDING = 'UPDATE_BOOKMARKS_PENDING';
export const UPDATE_BOOKMARKS_SUCCESS = 'UPDATE_BOOKMARKS_SUCCESS';
export const UPDATE_BOOKMARKS_ERROR = 'UPDATE_BOOKMARKS_ERROR';

export const DELETE_BOOKMARKS_PENDING = 'DELETE_BOOKMARKS_PENDING';
export const DELETE_BOOKMARKS_SUCCESS = 'DELETE_BOOKMARKS_SUCCESS';
export const DELETE_BOOKMARKS_ERROR = 'DELETE_BOOKMARKS_ERROR';

// ? BLOCK
export const REQ_BLOCK_PENDING = 'REQ_BLOCK_PENDING';
export const REQ_BLOCK_SUCCESS = 'REQ_BLOCK_SUCCESS';
export const REQ_BLOCK_ERROR = 'REQ_BLOCK_ERROR';

export const ADD_BLOCK_PENDING = 'ADD_BLOCK_PENDING';
export const ADD_BLOCK_SUCCESS = 'ADD_BLOCK_SUCCESS';
export const ADD_BLOCK_ERROR = 'ADD_BLOCK_ERROR';

export const UPDATE_BLOCK_PENDING = 'UPDATE_BLOCK_PENDING';
export const UPDATE_BLOCK_SUCCESS = 'UPDATE_BLOCK_SUCCESS';
export const UPDATE_BLOCK_ERROR = 'UPDATE_BLOCK_ERROR';

export const DELETE_BLOCK_PENDING = 'DELETE_BLOCK_PENDING';
export const DELETE_BLOCK_SUCCESS = 'DELETE_BLOCK_SUCCESS';
export const DELETE_BLOCK_ERROR = 'DELETE_BLOCK_ERROR';

// ? BLOCKS
export const REQ_BLOCKS_PENDING = 'REQ_BLOCKS_PENDING';
export const REQ_BLOCKS_SUCCESS = 'REQ_BLOCKS_SUCCESS';
export const REQ_BLOCKS_ERROR = 'REQ_BLOCKS_ERROR';

export const ADD_BLOCKS_PENDING = 'ADD_BLOCKS_PENDING';
export const ADD_BLOCKS_SUCCESS = 'ADD_BLOCKS_SUCCESS';
export const ADD_BLOCKS_ERROR = 'ADD_BLOCKS_ERROR';

export const UPDATE_BLOCKS_PENDING = 'UPDATE_BLOCKS_PENDING';
export const UPDATE_BLOCKS_SUCCESS = 'UPDATE_BLOCKS_SUCCESS';
export const UPDATE_BLOCKS_ERROR = 'UPDATE_BLOCKS_ERROR';

export const DELETE_BLOCKS_PENDING = 'DELETE_BLOCKS_PENDING';
export const DELETE_BLOCKS_SUCCESS = 'DELETE_BLOCKS_SUCCESS';
export const DELETE_BLOCKS_ERROR = 'DELETE_BLOCKS_ERROR';

// ? ARTICLE
export const REQ_ARTICLE_PENDING = 'REQ_ARTICLE_PENDING';
export const REQ_ARTICLE_SUCCESS = 'REQ_ARTICLE_SUCCESS';
export const REQ_ARTICLE_ERROR = 'REQ_ARTICLE_ERROR';

export const ADD_ARTICLE_PENDING = 'ADD_ARTICLE_PENDING';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_ERROR = 'ADD_ARTICLE_ERROR';

export const UPDATE_ARTICLE_PENDING = 'UPDATE_ARTICLE_PENDING';
export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_ERROR = 'UPDATE_ARTICLE_ERROR';

export const DELETE_ARTICLE_PENDING = 'DELETE_ARTICLE_PENDING';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_ERROR = 'DELETE_ARTICLE_ERROR';

// ? ARTICLES
export const REQ_ARTICLES_PENDING = 'REQ_ARTICLES_PENDING';
export const REQ_ARTICLES_SUCCESS = 'REQ_ARTICLES_SUCCESS';
export const REQ_ARTICLES_ERROR = 'REQ_ARTICLES_ERROR';

export const ADD_ARTICLES_PENDING = 'ADD_ARTICLES_PENDING';
export const ADD_ARTICLES_SUCCESS = 'ADD_ARTICLES_SUCCESS';
export const ADD_ARTICLES_ERROR = 'ADD_ARTICLES_ERROR';

export const UPDATE_ARTICLES_PENDING = 'UPDATE_ARTICLES_PENDING';
export const UPDATE_ARTICLES_SUCCESS = 'UPDATE_ARTICLES_SUCCESS';
export const UPDATE_ARTICLES_ERROR = 'UPDATE_ARTICLES_ERROR';

export const DELETE_ARTICLES_PENDING = 'DELETE_ARTICLES_PENDING';
export const DELETE_ARTICLES_SUCCESS = 'DELETE_ARTICLES_SUCCESS';
export const DELETE_ARTICLES_ERROR = 'DELETE_ARTICLES_ERROR';

// ? CompanyData
export const REQ_COMPANYDATA_PENDING = 'REQ_COMPANYDATA_PENDING';
export const REQ_COMPANYDATA_SUCCESS = 'REQ_COMPANYDATA_SUCCESS';
export const REQ_COMPANYDATA_ERROR = 'REQ_COMPANYDATA_ERROR';

export const ADD_COMPANYDATA_PENDING = 'ADD_COMPANYDATA_PENDING';
export const ADD_COMPANYDATA_SUCCESS = 'ADD_COMPANYDATA_SUCCESS';
export const ADD_COMPANYDATA_ERROR = 'ADD_COMPANYDATA_ERROR';

export const UPDATE_COMPANYDATA_PENDING = 'UPDATE_COMPANYDATA_PENDING';
export const UPDATE_COMPANYDATA_SUCCESS = 'UPDATE_COMPANYDATA_SUCCESS';
export const UPDATE_COMPANYDATA_ERROR = 'UPDATE_COMPANYDATA_ERROR';

export const DELETE_COMPANYDATA_PENDING = 'DELETE_COMPANYDATA_PENDING';
export const DELETE_COMPANYDATA_SUCCESS = 'DELETE_COMPANYDATA_SUCCESS';
export const DELETE_COMPANYDATA_ERROR = 'DELETE_COMPANYDATA_ERROR';
